site_name: florian-hild.de
site_url: https://florian-hild.de/
site_author: Florian Hild
site_description: "A personal notes blog"
copyright: "This is a personal notes blog. CC BY-SA 4.0 Florian Hild"

theme:
  name: null
  custom_dir: cinder
  colorscheme: github
  highlightjs: true
  hljs_languages:
        - yaml
        - python
        - dos
  disable_nav_previous_next: true
  collapse_toc: true

nav:
  - Home: index.md

markdown_extensions:
  - codehilite
  - admonition
  - footnotes
  - sane_lists
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - toc:
        permalink: "#"

plugins:
  - git-revision-date
  - rss:
        match_path: "blog/.*"
        date_from_meta:
            as_creation: "date_published"

extra:
  include_search: false
